### ISSUE TITLE
Plant Enhancements?

### ISSUE THREAD

**Issue by RinMaru** [SonicFreak94/sadx-fixed-edition#4]
So plants in Mystic Ruins animate when you walk up to them and some even sway by themselves would it be possible to give these animations to all plants in the game? Emerald Coast or Red Mountain would look more lively if the plants swayed and reacted to you walking over them.

**Comment by michael-fadely** [comment]
That falls out of the scope of this project. SADX:FE is focused primarily on restoring functionality and fixing bugs, not pure enhancements.

**Comment by RinMaru** [comment]
Alright thanks for the answer
