### ISSUE TITLE
Lost World Act 2 - Active wall panel textures not mirrored.

### ISSUE THREAD

**Issue by michael-fadely** [SonicFreak94/sadx-fixed-edition#6]
![sonic 2017-05-13 07-35-14-01](https://cloud.githubusercontent.com/assets/920569/26025916/fb49fa3c-37ae-11e7-9d44-62d4c54101f4.png)
![sonic 2017-05-13 07-35-18-98](https://cloud.githubusercontent.com/assets/920569/26025917/fd3739a4-37ae-11e7-848f-4558125ba863.png)

**Comment by RinMaru** [comment]
this is fixed in the DC mods lol

**Comment by michael-fadely** [comment]
I'm sure it is. The GameCube and Dreamcast versions of the game use native rendering pipeline texture mirroring, but the PC version dropped it for some reason--even though it works just fine! Consequently, the PC version has many notably lower resolution pre-mirrored versions of many textures. This appears to be one of many cases where they missed a texture.

**Comment by RinMaru** [comment]
Yea Ive seen a few of them when comparing PVMs. The PC version really got the short end plus every texture in PC has compression artifacts

**Comment by PiKeyAr** [comment]
The NJS_MODEL_SADX for the wall panel is at 201CE60 (memory). It requires a mirrored version of both normal and lit-up textures. The non-mirrored model is in SA1's STG07.BIN 00142710 (NJS_OBJECT). I just unmirrored all textures and did this:
*(NJS_MODEL_SADX*)0x201CE60 = attach_001426E8; //TPanel

**Comment by michael-fadely** [comment]
I just modified the textures for this case using the best assets from GC and DC. Considering this fixed.
