### ISSUE TITLE
Sonic - Leftover incomplete stretched shoe model

### ISSUE THREAD

**Issue by michael-fadely** [SonicFreak94/sadx-fixed-edition#7]
This is a leftover from the Dreamcast version which used a stretched version of the shoe as a morph target to emulate the classic Genesis stretched feet thing.

![sonic 2015-04-28 08-23-51-428](https://cloud.githubusercontent.com/assets/920569/26026758/ca92968c-37be-11e7-866c-476f46546a11.png)

**Comment by RinMaru** [comment]
fans will be happy about this ^^
